user_account/urls.py
from django.urls import path
from user_account import views as user_views
from .views import password_reset_request, password_reset_set_password, ProfileView

app_name = 'user_account'

urlpatterns = [
    path('', user_views.home_view, name='home'),
    path('home/', user_views.home_view, name='home'),
    path('about/', user_views.about_view, name='about'),
    # Authentication
    path('login/', user_views.login_user_view, name='login'),
    path('logout/', user_views.logout_user_view, name='logout'),
    # Profile Page
    path('create_account/', user_views.create_account_view, name='create_account'),
    path('profile/', ProfileView.as_view(), name='profile_view'),
    path('profile_update/', user_views.profile_update, name='profile_update'),
    # Password Reset
    path('password_reset_request/', password_reset_request, name='password_reset_request'),
    path('password_reset_set_password/<uidb64>/<token>/', password_reset_set_password,
         name='password_reset_set_password'),
]

user_account_system/urls.py
"""
URL configuration for user_account_system project.

"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_account.urls')),
]

# Serve static & media files for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_account/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from PIL import Image


# Custom User Model
# CustomUserManager class is a custom manager for the CustomUser model.
# Managers are used to encapsulate the logic for querying and creating instances of a model.
class CustomUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        # Ensure that username is provided
        if not username:
            raise ValueError('The Username field must be set')
        # Create a new user instance with provided fields
        user = self.model(username=username, email=email, **extra_fields)
        # Set password and save user
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        # Ensure that user is staff and superuser
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        # Create a new superuser using create_user method
        return self.create_user(username, email, password, **extra_fields)


# The actual Custom User
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, blank=True, null=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    STATES = (
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    )
    state = models.CharField(max_length=2, choices=STATES, blank=True, null=True)

    # Custom manager for user model
    objects = CustomUserManager()

    # Field used for authentication
    USERNAME_FIELD = 'username'

    # Required fields for creating a user through command line
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"


# Profile Model
class Profile(models.Model):
    custom_user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=100)
    avatar = models.ImageField(default="avatars/default.png", upload_to="avatars/",
                               height_field=None, width_field=None, max_length=None)
    player_bio = models.TextField(blank=True, null=True)

    # Avatar Resize on Profile Page
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            img = Image.open(self.avatar.path)

            if img.height > 200 or img.width > 200:
                img_size = (200, 200)
                img.thumbnail(img_size)
                img.save(self.avatar.path)

    # Output
    def __str__(self):
        return f'{self.custom_user.username} Profile'


# Login & Logout Timestamp
class AuthenticationLog(models.Model):
    custom_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    login_timestamp = models.DateTimeField()
    logout_timestamp = models.DateTimeField(null=True, blank=True)

    # Output
    def __str__(self):
        return f'Last login {self.logout_timestamp} & logout {self.logout_timestamp}'

user_account/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect
from django.contrib.auth import login, user_logged_out, get_user_model
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode
from django.views.generic import DetailView

from .forms import CreateAccountForm, ProfileForm, UserUpdateForm, CustomSetPasswordForm
from .models import Profile


# Home View
def home_view(request):
    return render(request, 'home.html')


# About View
def about_view(request):
    return render(request, 'about.html')


# Create User Account
def create_account_view(request):
    if request.method == 'POST':
        create_account_form = CreateAccountForm(request.POST)
        if create_account_form.is_valid():
            create_account_form.save()
            messages.success(request, 'Your account has been created. You can log in now!')
            return redirect('user_account:login')
    else:
        create_account_form = CreateAccountForm()

    context = {'create_account_form': create_account_form}
    return render(request, 'authentication/create_account.html', context)


# Login User
def login_user_view(request):
    login_form = AuthenticationForm()

    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            return redirect('user_account:home')

    context = {'login_form': login_form}
    return render(request, 'authentication/login.html', context)


# Logout User
def logout_user_view(request):
    if request.session.session_key:
        # Dispatch the built-in Django signal 'user_logged_out' to notify other parts of the application
        # that the user has been logged out.
        user_logged_out.send(sender=request.__class__, request=request, user=request.user)
        # Delete the session
        request.session.flush()
        # logs out the user by removing the authentication status from the current request.
        request.user = AnonymousUser()

    return redirect('user_account:login')


# Password Reset Feature
# Password Reset Form to send the reset password link to the user.
def password_reset_request(request):
    if request.method == 'POST':
        reset_form = PasswordResetForm(request.POST)
        if reset_form.is_valid():
            reset_form.save(
                request=request,
                from_email='info@maverickanalyzers.conqueringtechnology.com',
                email_template_name='password/password_reset_email_body.html',
                subject_template_name='password/password_reset_subject.txt',
            )
            messages.success(request, 'We have emailed you instructions for resetting your password, if an account exists with the email you entered. You will receive a reset link shortly.')
            return redirect('user_account:login')
    else:
        reset_form = PasswordResetForm()

    context = {'reset_form': reset_form}
    return render(request, 'password/password_reset_request.html', context)


# Set New Password Form
def password_reset_set_password(request, uidb64, token):
    custom_user_model = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = custom_user_model._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, custom_user_model.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            set_password_form = CustomSetPasswordForm(user, request.POST)
            if set_password_form.is_valid():
                set_password_form.save()
                messages.success(request, 'Your password has been successfully reset.')
                return redirect('user_account:login')
        else:
            set_password_form = CustomSetPasswordForm(user)

        context = {'set_password_form': set_password_form}
        return render(request, 'password/password_reset_set_password.html', context)
    else:
        messages.error(request, 'The password reset link is invalid or has expired.')
        return redirect('user_account:password_reset_request')


# Profile
# Profile View
@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProfileView(DetailView):
    model = Profile
    template_name = 'profile/profile.html'

    # Retrieve logged in user data
    def get_object(self, queryset=None):
        return Profile.objects.get(custom_user=self.request.user)


# Profile & Custom User Update
@login_required(login_url='/login/')
def profile_update(request):
    if request.method == 'POST':
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_update_form.is_valid() and profile_form.is_valid():
            user_update_form.save()
            profile_form.save()
            messages.success(request, f'Your account has been updated.')
            return redirect('user_account:profile_view')
    else:
        user_update_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    context = {
        'user_update_form': user_update_form,
        'profile_form': profile_form
    }
    return render(request, 'profile/profile_update.html', context)

user_account/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock styles %}
{% block title %}Profile - Spielcraft Game{% endblock title%}
{% block content %}
    <div class="container py-4">
        {# Show Avatar#}
        <div class="d-flex align-items-center">
            <img src="{{profile.avatar.url}}" class="img-fluid rounded-circle me-4 profile__avatar" alt="Player Avatar">
            <h1>{{profile.display_name}}</h1>
        </div>

        {# Biography Section #}
        <div class="my-4">
            <h3 class="mb-3">Biography</h3>
            <p>{{profile.player_bio}}</p>
        </div>

        {# Profile/User Details Section #}
        <div class="row">
            <h3 class="mb-4">Profile Details</h3>
            <div class="col-lg-6 col-md-6 d-flex justify-content-center align-items-center">
                <div class="text-center mb-4">
                    <h4>{{ user.username }}</h4>
                    <div class="my-2 profile__custom_border_bottom"></div>
                    <h5>Username</h5>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 d-flex justify-content-center align-items-center">
                <div class="text-center mb-4">
                    <h4>{{ user.email }}</h4>
                    <div class="my-2 profile__custom_border_bottom"></div>
                    <h5>Email</h5>
                </div>
            </div>

        </div>

        {# Profile Details #}
        <div class="row">
            <div class="col-lg-6 col-md-6 d-flex justify-content-center align-items-center">
                <div class="text-center mb-4">
                    <h4>{{ user.first_name }}</h4>
                    <div class="my-2 profile__custom_border_bottom"></div>
                    <h5>First Name</h5>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 d-flex justify-content-center align-items-center">
                <div class="text-center mb-4">
                    <h4>{{ user.last_name }}</h4>
                    <div class="my-2 profile__custom_border_bottom"></div>
                    <h5>Last Name</h5>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6 d-flex justify-content-center align-items-center">
                <div class="text-center mb-4">
                    <h4>{{ profile.display_name }}</h4>
                    <div class="my-2 profile__custom_border_bottom"></div>
                    <h5>Display Name</h5>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 d-flex justify-content-center align-items-center">
                <div class="text-center mb-4">
                    {# Since you've defined the choices for the state field in your model, Django will generate the get_<field_name>_display method for you. #}
                    <h4>{{ user.get_state_display }}</h4>
                    <div class="my-2 profile__custom_border_bottom"></div>
                    <h5>State</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock script %}

user_account/templates/profile/profile_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock styles %}
{% block title %}Update Profile - Spielcraft Games{% endblock %}
{% block content %}
    {# Update Profile Button #}
    <div class="container p-4">
        {# Show Player Personal Details #}
        <div class="d-flex flex-column">
            <img src="{{ user.profile.avatar.url }}" class="img-fluid rounded-circle me-4 profile__avatar" alt="Player Avatar">
            <h2>{{ user.profile.display_name }}</h2>
        </div>

        {# Display Profile Update Form #}
        <form class="p-4" method="POST" enctype="multipart/form-data" action="{% url 'user_account:profile_update' %}" novalidate>
            {# Update Profile Button #}
            <div class="d-flex justify-content-between mb-2">
                <div>
                    <h1>Profile</h1>
                    <p>View and edit your personal information below.</p>
                </div>
                <div>
                    <a class="btn btn-outline-danger me-3 mb-3" href="{% url 'user_account:profile_view' %}">Discard</a>
                    <button type="submit" class="btn btn-danger mb-3">Update Info</button>
                </div>
            </div>
            <div class="row">
                <div class="my-3">
                    <h3 class="mb-2">Profile Info</h3>
                    <p>Update your personal information.</p>
                </div>
                <div class="row">
                    <div class="col-md-5 mx-auto">
                        <fieldset>
                            {% csrf_token %}
                            {{ user_update_form | crispy }}
                        </fieldset>
                    </div>
                    <div class="col-md-5 mt-4 mt-md-0 mx-auto">
                        <fieldset>
                            {{ profile_form | crispy }}
                        </fieldset>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block script %}{% endblock script %}