user_account/urls.py
from django.urls import path
from user_account import views as user_views
from .views import password_reset_request, password_reset_set_password, ProfileView

app_name = 'user_account'

urlpatterns = [
    path('', user_views.home_view, name='home'),
    path('home/', user_views.home_view, name='home'),
    path('about/', user_views.about_view, name='about'),
    # Authentication
    path('login/', user_views.login_user_view, name='login'),
    path('logout/', user_views.logout_user_view, name='logout'),
    # Profile Page
    path('create_account/', user_views.create_account_view, name='create_account'),
    path('profile/', ProfileView.as_view(), name='profile_view'),
    path('profile_update/', user_views.profile_update, name='profile_update'),
    # Password Reset
    path('password_reset_request/', password_reset_request, name='password_reset_request'),
    path('password_reset_set_password/<uidb64>/<token>/', password_reset_set_password,
         name='password_reset_set_password'),
]

user_account_system/urls.py
"""
URL configuration for user_account_system project.

"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_account.urls')),
]

# Serve static & media files for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm

from .models import CustomUser, Profile


# Create User Account Form
class CreateAccountForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove the "password is too similar to the last name" validator
        self.fields['password1'].validators = []
        self.fields['password2'].validators = []

    # Add Attribute Class that are Not inherited by UserCreationForm for Bootstrap class
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    state = forms.ChoiceField(
        choices=CustomUser.STATES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'state', 'username', 'password1', 'password2']
        labels = {
            'password1': 'Password',
            'password2': 'Confirm Password',
        }

    def __init__(self, *args, **kwargs):
        super(CreateAccountForm, self).__init__(*args, **kwargs)
        # Add Attribute are inherited from UserCreationForm for Bootstrap class
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

        # Set custom help text for password1 field
        self.fields['password1'].help_text = (
            "<ul>"
            "<li>Use at least 8 characters.</li>"
            "<li>Use uppercase and lowercase characters.</li>"
            "<li>Use at least one number.</li>"
            "<li>At least use one special character (!@#$%^&*).</li>"
            "</ul>"
        )

    # Clean Email Data
    def clean_email(self):
        email = self.cleaned_data['email']

        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists.")
        return email.lower()

    # Clean Username Data
    def clean_username(self):
        username = self.cleaned_data['username']

        if CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists.")
        return username.lower()

    # Custom password validation
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        # Custom password validation logic
        if len(password1) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        if not any(char.isupper() for char in password1):
            raise forms.ValidationError("Password must contain at least one uppercase letter.")
        if not any(char.islower() for char in password1):
            raise forms.ValidationError("Password must contain at least one lowercase letter.")
        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError("Password must contain at least one digit.")
        if not any(char in '!@#$%^&*' for char in password1):
            raise forms.ValidationError("Password must contain at least one special character (!@#$%^&*).")

        return password1


def clean_password2(self):
    password1 = self.cleaned_data.get("password1")
    password2 = self.cleaned_data.get("password2")
    if password1 and password2 and password1 != password2:
        raise forms.ValidationError(
            self.error_messages['password_mismatch'],
            code='password_mismatch',
        )

    return password2


# Update Password
class CustomSetPasswordForm(SetPasswordForm):
    # Custom password validation
    def clean_new_password1(self):
        password1 = self.cleaned_data.get('new_password1')

        # Custom password validation logic
        if len(password1) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        if not any(char.isupper() for char in password1):
            raise forms.ValidationError("Password must contain at least one uppercase letter.")
        if not any(char.islower() for char in password1):
            raise forms.ValidationError("Password must contain at least one lowercase letter.")
        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError("Password must contain at least one digit.")
        if not any(char in '!@#$%^&*' for char in password1):
            raise forms.ValidationError("Password must contain at least one special character (!@#$%^&*).")

        return password1

    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")

        # Check if passwords match
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )

        return password2

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set custom help text for password1 field
        self.fields['new_password1'].help_text = (
            "<ul>"
            "<li>Use at least 8 characters.</li>"
            "<li>Use uppercase and lowercase characters.</li>"
            "<li>Use at least one number.</li>"
            "<li>At least use one special character (!@#$%^&*).</li>"
            "</ul>"
        )


# Profile
# Create and Update Profile Form
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['display_name', 'avatar', 'player_bio']

    # Clean Display Name Data
    def clean_display_name(self):
        display_name = self.cleaned_data['display_name']

        # Check if the display name already exists excluding the current instance
        existing_display_name = Profile.objects.filter(display_name=display_name).exclude(pk=self.instance.pk)
        if existing_display_name.exists():
            raise forms.ValidationError("Display Name already exists.")
        return display_name.lower()


# Update CustomUser Form
class UserUpdateForm(forms.ModelForm):
    # Add Fields to Update CustomUser Form
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    state = forms.ChoiceField(
        choices=CustomUser.STATES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'state']

    # Add Attribute Class to existing Fields for Bootstrap
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'

user_account/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect
from django.contrib.auth import login, user_logged_out, get_user_model
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode
from django.views.generic import DetailView

from .forms import CreateAccountForm, ProfileForm, UserUpdateForm, CustomSetPasswordForm
from .models import Profile


# Home View
def home_view(request):
    return render(request, 'home.html')


# About View
def about_view(request):
    return render(request, 'about.html')


# Create User Account
def create_account_view(request):
    if request.method == 'POST':
        create_account_form = CreateAccountForm(request.POST)
        if create_account_form.is_valid():
            create_account_form.save()
            messages.success(request, 'Your account has been created. You can log in now!')
            return redirect('user_account:login')
    else:
        create_account_form = CreateAccountForm()

    context = {'create_account_form': create_account_form}
    return render(request, 'authentication/create_account.html', context)


# Login User
def login_user_view(request):
    login_form = AuthenticationForm()

    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            return redirect('user_account:home')

    context = {'login_form': login_form}
    return render(request, 'authentication/login.html', context)


# Logout User
def logout_user_view(request):
    if request.session.session_key:
        # Dispatch the built-in Django signal 'user_logged_out' to notify other parts of the application
        # that the user has been logged out.
        user_logged_out.send(sender=request.__class__, request=request, user=request.user)
        # Delete the session
        request.session.flush()
        # logs out the user by removing the authentication status from the current request.
        request.user = AnonymousUser()

    return redirect('user_account:login')


# Password Reset Feature
# Password Reset Form to send the reset password link to the user.
def password_reset_request(request):
    if request.method == 'POST':
        reset_form = PasswordResetForm(request.POST)
        if reset_form.is_valid():
            reset_form.save(
                request=request,
                from_email='info@maverickanalyzers.conqueringtechnology.com',
                email_template_name='password/password_reset_email_body.html',
                subject_template_name='password/password_reset_subject.txt',
            )
            messages.success(request, 'We have emailed you instructions for resetting your password, if an account exists with the email you entered. You will receive a reset link shortly.')
            return redirect('user_account:login')
    else:
        reset_form = PasswordResetForm()

    context = {'reset_form': reset_form}
    return render(request, 'password/password_reset_request.html', context)


# Set New Password Form
def password_reset_set_password(request, uidb64, token):
    custom_user_model = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = custom_user_model._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, custom_user_model.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            set_password_form = CustomSetPasswordForm(user, request.POST)
            if set_password_form.is_valid():
                set_password_form.save()
                messages.success(request, 'Your password has been successfully reset.')
                return redirect('user_account:login')
        else:
            set_password_form = CustomSetPasswordForm(user)

        context = {'set_password_form': set_password_form}
        return render(request, 'password/password_reset_set_password.html', context)
    else:
        messages.error(request, 'The password reset link is invalid or has expired.')
        return redirect('user_account:password_reset_request')


# Profile
# Profile View
@method_decorator(login_required(login_url='/login/'), name='dispatch')
class ProfileView(DetailView):
    model = Profile
    template_name = 'profile/profile.html'

    # Retrieve logged in user data
    def get_object(self, queryset=None):
        return Profile.objects.get(custom_user=self.request.user)


# Profile & Custom User Update
@login_required(login_url='/login/')
def profile_update(request):
    if request.method == 'POST':
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_update_form.is_valid() and profile_form.is_valid():
            user_update_form.save()
            profile_form.save()
            messages.success(request, f'Your account has been updated.')
            return redirect('user_account:profile_view')
    else:
        user_update_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    context = {
        'user_update_form': user_update_form,
        'profile_form': profile_form
    }
    return render(request, 'profile/profile_update.html', context)

user_account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% load static %}
    <!-- Bootstrap5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% bootstrap_css %}
    <!-- Font Awesome CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Arial|Helvetica&display=swap">
    <!-- External CSS File -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}{% endblock styles %}
    <title>{% block title %}Maverick Analyzers{% endblock %}</title>
</head>
<body class="bg-black text-light">
    <header>
        {# Navigation Bar #}
        {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-dark d-flex justify-content-center align-items-center base__navbar_position">
                <div class="pt-2">
                    {% if request.path == '/create_account/' %}
                        <h1 class="">Spielcraft Games</h1>
                    {% elif request.path == '/login/' %}
                        <h1 class="">Spielcraft Games</h1>
                    {% elif request.path == '/password_reset_request/' %}
                        <h1 class="">Spielcraft Games</h1>
                    {% elif '/password_reset_set_password/' in request.path %}
                        {% with request.path|slice:"/password_reset_set_password/"|slice:"6:" as path_suffix %}
                            {% with path_suffix|slice:"/"|slice:"1:" as uidb64 %}
                                {% with path_suffix|slice:"/"|slice:"11:" as token %}
                                    <h1 class="">Spielcraft Games</h1>
                                {% endwith %}
                            {% endwith %}
                        {% endwith %}
                    {% elif request.path == '/home/' or request.path == '/' %}
                        <h1 class="">Spielcraft Games</h1>
                    {% elif request.path == '/about/' %}
                        <div class="text-center mb-4">
                            <h1 class="mb-3">About Us</h1>
                            <h6 class="text-danger">Learn More About Our Free Online Tabletop Game</h6>
                        </div>
                    {% elif request.path == '/profile/' or request.path == '/profile_update/'%}
                        <h1>{{ user.profile.display_name }}'s Profile</h1>
                    {% endif %}
                </div>

                {# Navigation Bar Logo #}
               <div class="base__nav_logo">
                   {# Spielcraft Games Logo #}
                   <a class="navbar-brand ms-2" href="{% url 'user_account:home' %}">
                       <img class="d-inline-block align-top" src="{% static 'images/SpielcraftGamesLogoWhite.png' %}" width="100" height="100" alt="Spielcraft Games Logo">
                   </a>
               </div>

                {# Navigation Bar links #}
               <div class="d-flex align-items-center base__nav_links me-2">
                   {# Navigation Toggle Menu Button #}
                   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#MainNavbar" aria-controls="MainNavbar" aria-expanded="false" aria-label="Toggle Navigation">
                      <span class="navbar-toggler-icon"></span>
                   </button>

                   <div class="collapse navbar-collapse" id="MainNavbar">
                       {# Navigation Bar Links #}
                       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                           <li class="nav-item">
                               <a class="nav-link {% if request.path == '/home/' or request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'user_account:home' %}">Home</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link {% if request.path == '/about/' %}active{% endif %}" href="{% url 'user_account:about' %}">About</a>
                           </li>
                      </ul>

                      {# Nav Bar Logic to show login or logout if user is authenticated #}
                      <ul class="navbar-nav me-1">
                          {% if user.is_authenticated %}
                              <li class="nav-item">
                                  <a class="nav-link {% if request.path == '/profile/' %}active{% endif %}"
                                   href="{% url 'user_account:profile_view' %}">Profile</a>
                              </li>
                              <li class="border nav-item dropdown">
                                  <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      <i class="fa-regular fa-circle-user"></i>
                                  </a>
                                  {# Navigation Dropdown for Edit Profile and Logoout #}
                                  <ul class="dropdown-menu dropdown-menu-end me-2 border text-center" aria-labelledby="navbarDropdown">
                                      <li><a class="dropdown-item {% if request.path == '/profile_update/' %}active{% endif %}"
                                             href="{% url 'user_account:profile_update' %}">My Account</a></li>
                                      <li><hr class="dropdown-divider text-light mx-2"></li>
                                      <li><a class="dropdown-item  {% if request.path == '/logout/' %}active{% endif %}" href="{% url 'user_account:logout' %}">Logout</a></li>
                                  </ul>
                              </li>
                          {% else %}
                              <li class="nav-item me-1">
                                  <a class="nav-link {% if request.path == '/login/' %}active{% endif %}" href="{% url 'user_account:login' %}">Login</a>
                              </li>
                          {% endif %}
                      </ul>
                  </div>
               </div>
           </nav>
        {% endblock navbar %}
    </header>
    <main>
        {# Display Successful/Error Messages  #}
        <div class="text-center">
            {% bootstrap_messages %}
        </div>

        {% block content %}{% endblock %}
    </main>
    <footer>

    </footer>
    <!-- JQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <!-- Bootstrap5 CDN -->
    {% bootstrap_javascript %}
    {% block script %}{% endblock script %}
</body>
</html>

user_account/templates/home.html
{% extends "base.html" %}
{% block title %}Home - Spielcraft Games{% endblock %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock styles %}
{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center text-center mt-4 home__splashscreen">
    {# Welcom Header #}
    <h1 class="display-1 mb-4">Welcome</h1>
    {# Welcom Message #}
    <div class="container">
        <p class="text-center">
            Gaming online is exploding, and our company has leveraged the power of replicating the tactile and social aspects of strategic tabletop gaming while enhancing it with digital advantages like immersive online gameplay experience, accessibility, and convenience. Spielcraft Games is an online trading game that consists of two players. Players will login to a match-making system where they are paired with another player to play the game. To learn more about the game click the "Learn More" button.
        </p>
    </div>

    {# Link to About page #}
    <a class="btn btn-danger btn-lg mt-3" href="{% url 'user_account:about' %}">Learn More</a>
</div>
{% endblock %}
{% block script %}{% endblock script %}